# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\Dropbox\pw_prefs\RnD\tools\pw_scriptEditor\multi_script_editor\widgets\scriptEditor.ui'
#
# Created: Mon Apr 06 09:46:03 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!


from vendor.Qt.QtCore import QMetaObject, QRect, Qt
from vendor.Qt.QtWidgets import (
    QAction,
    QApplication,
    QFrame,
    QMenu,
    QMenuBar,
    QSplitter,
    QToolBar,
    QVBoxLayout,
    QWidget,
)


class Ui_scriptEditor(object):
    def setupUi(self, scriptEditor):
        scriptEditor.setObjectName("scriptEditor")
        scriptEditor.resize(1280, 720)
        self.centralwidget = QWidget(scriptEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QSplitter(self.frame_2)
        self.splitter.setOrientation(Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.out_ly = QVBoxLayout(self.verticalLayoutWidget)
        self.out_ly.setContentsMargins(0, 0, 0, 0)
        self.out_ly.setObjectName("out_ly")
        self.verticalLayoutWidget_2 = QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.in_ly = QVBoxLayout(self.verticalLayoutWidget_2)
        self.in_ly.setContentsMargins(0, 0, 0, 0)
        self.in_ly.setObjectName("in_ly")
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.frame_2)
        scriptEditor.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(scriptEditor)
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.file_menu = QMenu(self.menubar)
        self.file_menu.setTearOffEnabled(True)
        self.file_menu.setObjectName("file_menu")
        self.help_menu = QMenu(self.menubar)
        self.help_menu.setTearOffEnabled(True)
        self.help_menu.setObjectName("help_menu")
        self.tools_menu = QMenu(self.menubar)
        self.tools_menu.setTearOffEnabled(True)
        self.tools_menu.setObjectName("tools_menu")
        self.options_menu = QMenu(self.menubar)
        self.options_menu.setTearOffEnabled(True)
        self.options_menu.setObjectName("options_menu")

        self.run_menu = QMenu(self.menubar)
        self.run_menu.setTearOffEnabled(True)
        self.run_menu.setObjectName("run_menu")
        self.view_menu = QMenu(self.menubar)
        self.view_menu.setTearOffEnabled(True)
        self.view_menu.setObjectName("view_menu")
        self.theme_menu = QMenu(self.menubar)
        self.theme_menu.setObjectName("theme_menu")
        self.theme_menu.setTearOffEnabled(True)
        scriptEditor.setMenuBar(self.menubar)
        self.toolBar = QToolBar(scriptEditor)
        self.toolBar.setObjectName("toolBar")
        scriptEditor.addToolBar(Qt.TopToolBarArea, self.toolBar)
        self.clearHistory_act = QAction(scriptEditor)
        self.clearHistory_act.setObjectName("clearHistory_act")
        self.clear_exec_act = QAction(scriptEditor)
        self.clear_exec_act.setObjectName("clear_exec_act")
        self.print_command_act = QAction(scriptEditor)
        self.print_command_act.setObjectName("print_command_act")
        self.dir_act = QAction(scriptEditor)
        self.dir_act.setObjectName("dir_act")
        self.print_act = QAction(scriptEditor)
        self.print_act.setObjectName("print_act")
        self.help_act = QAction(scriptEditor)
        self.help_act.setObjectName("help_act")
        self.type_act = QAction(scriptEditor)
        self.type_act.setObjectName("type_act")
        self.quick_help_act = QAction(scriptEditor)
        self.quick_help_act.setObjectName("quick_help_act")
        self.save_act = QAction(scriptEditor)
        self.save_act.setObjectName("save_act")
        self.saveAs_act = QAction(scriptEditor)
        self.saveAs_act.setObjectName("saveAs_act")
        self.load_act = QAction(scriptEditor)
        self.load_act.setObjectName("load_act")
        self.exit_act = QAction(scriptEditor)
        self.exit_act.setObjectName("exit_act")
        self.openManual_act = QAction(scriptEditor)
        self.openManual_act.setObjectName("openManual_act")
        self.blenderManual_act = QAction(scriptEditor)
        self.blenderManual_act.setObjectName("blenderManual_act")
        self.python_act = QAction(scriptEditor)
        self.python_act.setObjectName("python_act")
        self.quickHelp_act = QAction(scriptEditor)
        self.quickHelp_act.setObjectName("quickHelp_act")
        self.qt_docs_act = QAction(scriptEditor)
        self.qt_docs_act.setObjectName("qt_docs_act")
        self.qt_modules_act = QAction(scriptEditor)
        self.qt_modules_act.setObjectName("qt_modules_act")
        self.maya_cmds_act = QAction(scriptEditor)
        self.maya_cmds_act.setObjectName("maya_cmds_act")
        self.houdini_hou_act = QAction(scriptEditor)
        self.houdini_hou_act.setObjectName("houdini_hou_act")
        self.houdini_envs_act = QAction(scriptEditor)
        self.houdini_envs_act.setObjectName("houdini_envs_act")
        self.nuke_dev_guide_act = QAction(scriptEditor)
        self.nuke_dev_guide_act.setObjectName("nuke_dev_guide_act")
        self.gaffer_docs_act = QAction(scriptEditor)
        self.gaffer_docs_act.setObjectName("gaffer_docs_act")
        self.gaffer_node_reference_act = QAction(scriptEditor)
        self.gaffer_node_reference_act.setObjectName("gaffer_node_reference_act")
        self.saveSeccion_act = QAction(scriptEditor)
        self.saveSeccion_act.setObjectName("saveSeccion_act")
        self.closeAllTabs_act = QAction(scriptEditor)
        self.closeAllTabs_act.setObjectName("closeAllTabs_act")
        self.quit_act = QAction(scriptEditor)
        self.quit_act.setObjectName("quit_act")
        self.tabToSpaces_act = QAction(scriptEditor)
        self.tabToSpaces_act.setObjectName("tabToSpaces_act")
        self.spacesToTabs_act = QAction(scriptEditor)
        self.spacesToTabs_act.setObjectName("spacesToTabs_act")
        self.always_ontop_act = QAction(scriptEditor)
        self.always_ontop_act.setObjectName("ontop_act")
        self.settingsFile_act = QAction(scriptEditor)
        self.settingsFile_act.setObjectName("settingsFile_act")
        self.set_font_act = QAction(scriptEditor)
        self.set_font_act.setObjectName("set_font_act")
        self.editTheme_act = QAction(scriptEditor)
        self.editTheme_act.setObjectName("editTheme_act")
        self.shortcuts_act = QAction(scriptEditor)
        self.shortcuts_act.setObjectName("shortcuts_act")
        self.documentation_act = QAction(scriptEditor)
        self.documentation_act.setObjectName("documentation_act")
        self.donate_act = QAction(scriptEditor)
        self.donate_act.setObjectName("donate_act")
        self.about_act = QAction(scriptEditor)
        self.about_act.setObjectName("about_act")
        self.execAll_act = QAction(scriptEditor)
        self.execAll_act.setObjectName("execAll_act")
        self.execLine_act = QAction(scriptEditor)
        self.execLine_act.setObjectName("execLine_act")
        self.execSel_act = QAction(scriptEditor)
        self.execSel_act.setObjectName("execSel_act")
        self.whitespace_act = QAction(scriptEditor)
        self.whitespace_act.setObjectName("whitespace_act")
        self.themeFontOnTabs_act = QAction(scriptEditor)
        self.themeFontOnTabs_act.setObjectName("themeFontOnTabs_act")
        self.themeFontOnTabs_act.setCheckable(True)
        self.out_wordWrap_act = QAction(scriptEditor)
        self.out_wordWrap_act.setObjectName("out_wordWrap_act")
        self.wordWrap_act = QAction(scriptEditor)
        self.wordWrap_act.setObjectName("wordWrap_act")
        self.clipboardManager_act = QAction(scriptEditor)
        self.clipboardManager_act.setObjectName("clipboardManager_act")
        self.copy_act = QAction(scriptEditor)
        self.copy_act.setObjectName("copy_act")
        self.cut_act = QAction(scriptEditor)
        self.cut_act.setObjectName("cut_act")
        self.paste_act = QAction(scriptEditor)
        self.paste_act.setObjectName("paste_act")
        self.addCursorsToLineEnds_act = QAction(scriptEditor)
        self.addCursorsToLineEnds_act.setObjectName("addCursorsToLineEnds_act")
        self.addCursorAbove_act = QAction(scriptEditor)
        self.addCursorAbove_act.setObjectName("addCursorAbove_act")
        self.addCursorBelow_act = QAction(scriptEditor)
        self.addCursorBelow_act.setObjectName("addCursorBelow_act")
        self.find_act = QAction(scriptEditor)
        self.find_act.setObjectName("find_act")
        self.replace_act = QAction(scriptEditor)
        self.replace_act.setObjectName("replace_act")
        self.gitAction_act = QAction(scriptEditor)
        self.gitAction_act.setObjectName("gitAction_act")
        self.gotoLine_act = QAction(scriptEditor)
        self.gotoLine_act.setObjectName("gotoLine_act")
        self.goToSymbol_act = QAction(scriptEditor)
        self.goToSymbol_act.setObjectName("goToSymbol_act")
        self.undo_act = QAction(scriptEditor)
        self.undo_act.setObjectName("undo_act")
        self.redo_act = QAction(scriptEditor)
        self.redo_act.setObjectName("redo_act")
        self.duplicateLine_act = QAction(scriptEditor)
        self.duplicateLine_act.setObjectName("duplicateLine_act")
        self.deleteLine_act = QAction(scriptEditor)
        self.deleteLine_act.setObjectName("deleteLine_act")
        self.printHelp_act = QAction(scriptEditor)
        self.printHelp_act.setObjectName("printHelp_act")
        self.moveLineUp_act = QAction(scriptEditor)
        self.moveLineUp_act.setObjectName("moveLineUp_act")
        self.moveLineDown_act = QAction(scriptEditor)
        self.moveLineDown_act.setObjectName("moveLineDown_act")
        self.selectLine_act = QAction(scriptEditor)
        self.selectLine_act.setObjectName("selectLine_act")
        self.comment_cat = QAction(scriptEditor)
        self.comment_cat.setObjectName("comment_cat")
        self.add_quotes_act = QAction(scriptEditor)
        self.add_quotes_act.setObjectName("add_quotes_act")
        self.f_string_act = QAction(scriptEditor)
        self.f_string_act.setObjectName("f_string_act")
        self.showExplorer_act = QAction(scriptEditor)
        self.showExplorer_act.setObjectName("showExplorer_act")
        self.showExplorer_act.setCheckable(True)
        self.showOutline_act = QAction(scriptEditor)
        self.showOutline_act.setObjectName("showOutline_act")
        self.showOutline_act.setCheckable(True)
        self.showBreadcrumbs_act = QAction(scriptEditor)
        self.showBreadcrumbs_act.setObjectName("showBreadcrumbs_act")
        self.showBreadcrumbs_act.setCheckable(True)
        self.showOutput_act = QAction(scriptEditor)
        self.showOutput_act.setObjectName("showOutput_act")
        self.showOutput_act.setCheckable(True)
        self.syntaxCheck_act = QAction(scriptEditor)
        self.syntaxCheck_act.setObjectName("syntaxCheck_act")
        self.syntaxCheck_act.setCheckable(True)
        self.commandPalette_act = QAction(scriptEditor)
        self.commandPalette_act.setObjectName("commandPalette_act")
        self.outputBottom_act = QAction(scriptEditor)
        self.outputBottom_act.setObjectName("outputBottom_act")
        self.outputBottom_act.setCheckable(True)
        self.toggleMenus_act = QAction(scriptEditor)
        self.toggleMenus_act.setObjectName("toggleMenus_act")
        self.toggleMenus_act.setCheckable(True)
        self.toggleEditorToolbar_act = QAction(scriptEditor)
        self.toggleEditorToolbar_act.setObjectName("toggleEditorToolbar_act")
        self.toggleEditorToolbar_act.setCheckable(True)
        self.autoCloseDelimiters_act = QAction(scriptEditor)
        self.autoCloseDelimiters_act.setObjectName("autoCloseDelimiters_act")
        self.autoCloseDelimiters_act.setCheckable(True)
        self.quickTabSwitching_act = QAction(scriptEditor)
        self.quickTabSwitching_act.setObjectName("quickTabSwitching_act")
        self.quickTabSwitching_act.setCheckable(True)
        self.showStatusTips_act = QAction(scriptEditor)
        self.showStatusTips_act.setObjectName("showStatusTips_act")
        self.showStatusTips_act.setCheckable(True)
        self.autocomplete_act = QAction(scriptEditor)
        self.autocomplete_act.setObjectName("autocomplete_act")
        self.autocomplete_act.setCheckable(True)
        self.fuzzy_autocomplete_act = QAction(scriptEditor)
        self.fuzzy_autocomplete_act.setObjectName("fuzzy_autocomplete_act")
        self.fuzzy_autocomplete_act.setCheckable(True)
        self.show_docstrings_act = QAction(scriptEditor)
        self.show_docstrings_act.setObjectName("show_docstrings_act")
        self.show_docstrings_act.setCheckable(True)
        self.highlightAllOccurrences_act = QAction(scriptEditor)
        self.highlightAllOccurrences_act.setObjectName("highlightAllOccurrences_act")
        self.highlightAllOccurrences_act.setCheckable(True)
        self.occurrencesCaseSensitive_act = QAction(scriptEditor)
        self.occurrencesCaseSensitive_act.setObjectName("occurrencesCaseSensitive_act")
        self.occurrencesCaseSensitive_act.setCheckable(True)
        self.preferSingleQuotes_act = QAction(scriptEditor)
        self.preferSingleQuotes_act.setObjectName("preferSingleQuotes_act")
        self.preferSingleQuotes_act.setCheckable(True)
        self.selectNextOccurrence_act = QAction(scriptEditor)
        self.selectNextOccurrence_act.setObjectName("selectNextOccurrence_act")
        self.nextSelection_act = QAction(scriptEditor)
        self.nextSelection_act.setObjectName("nextSelection_act")
        self.previousSelection_act = QAction(scriptEditor)
        self.previousSelection_act.setObjectName("previousSelection_act")
        self.selectAllOccurrences_act = QAction(scriptEditor)
        self.selectAllOccurrences_act.setObjectName("selectAllOccurrences_act")
        self.showAutocomplete_act = QAction(scriptEditor)
        self.showAutocomplete_act.setObjectName("showAutocomplete_act")
        self.trimWhitespace_act = QAction(scriptEditor)
        self.trimWhitespace_act.setObjectName("trimWhitespace_act")
        self.trimAutoWhitespace_act = QAction(scriptEditor)
        self.trimAutoWhitespace_act.setObjectName("trimAutoWhitespace_act")
        self.trimAutoWhitespace_act.setCheckable(True)
        self.versionControl_act = QAction(scriptEditor)
        self.versionControl_act.setObjectName("versionControl_act")
        self.versionControl_act.setCheckable(True)
        self.diffTool_act = QAction(scriptEditor)
        self.diffTool_act.setObjectName("diffTool_act")
        self.file_menu.addAction(self.load_act)
        self.file_menu.addAction(self.save_act)
        self.file_menu.addAction(self.saveAs_act)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.closeAllTabs_act)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.diffTool_act)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.quit_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.quick_help_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.blenderManual_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.openManual_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.houdini_envs_act)
        self.help_menu.addAction(self.houdini_hou_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.maya_cmds_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.nuke_dev_guide_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.gaffer_docs_act)
        self.help_menu.addAction(self.gaffer_node_reference_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.python_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.qt_docs_act)
        self.help_menu.addAction(self.qt_modules_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.shortcuts_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.documentation_act)
        self.help_menu.addAction(self.printHelp_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.donate_act)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.about_act)
        self.tools_menu.addAction(self.undo_act)
        self.tools_menu.addAction(self.redo_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.clipboardManager_act)
        self.tools_menu.addAction(self.copy_act)
        self.tools_menu.addAction(self.cut_act)
        self.tools_menu.addAction(self.paste_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.add_quotes_act)
        self.tools_menu.addAction(self.comment_cat)
        self.tools_menu.addAction(self.f_string_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.deleteLine_act)
        self.tools_menu.addAction(self.duplicateLine_act)
        self.tools_menu.addAction(self.moveLineUp_act)
        self.tools_menu.addAction(self.moveLineDown_act)
        self.tools_menu.addAction(self.selectLine_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.addCursorsToLineEnds_act)
        self.tools_menu.addAction(self.addCursorAbove_act)
        self.tools_menu.addAction(self.addCursorBelow_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.nextSelection_act)
        self.tools_menu.addAction(self.previousSelection_act)
        self.tools_menu.addAction(self.selectNextOccurrence_act)
        self.tools_menu.addAction(self.selectAllOccurrences_act)
        self.tools_menu.addAction(self.commandPalette_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.find_act)
        self.tools_menu.addAction(self.replace_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.gitAction_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.gotoLine_act)
        self.tools_menu.addAction(self.goToSymbol_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.spacesToTabs_act)
        self.tools_menu.addAction(self.tabToSpaces_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.trimWhitespace_act)
        self.tools_menu.addSeparator()
        self.tools_menu.addAction(self.showAutocomplete_act)

        self.theme_menu.addAction(self.editTheme_act)
        self.theme_menu.addSeparator()
        self.options_menu.addSeparator()
        self.options_menu.addAction(self.autocomplete_act)
        self.options_menu.addAction(self.fuzzy_autocomplete_act)
        self.options_menu.addAction(self.show_docstrings_act)
        self.options_menu.addAction(self.syntaxCheck_act)
        self.options_menu.addSeparator()
        self.options_menu.addAction(self.autoCloseDelimiters_act)
        self.options_menu.addSeparator()
        self.options_menu.addAction(self.highlightAllOccurrences_act)
        self.options_menu.addAction(self.occurrencesCaseSensitive_act)
        self.options_menu.addSeparator()
        self.options_menu.addAction(self.preferSingleQuotes_act)
        self.options_menu.addSeparator()
        self.options_menu.addAction(self.quickTabSwitching_act)
        self.options_menu.addSeparator()
        self.options_menu.addAction(self.showStatusTips_act)
        self.options_menu.addSeparator()
        self.options_menu.addAction(self.whitespace_act)
        self.options_menu.addAction(self.themeFontOnTabs_act)
        self.options_menu.addAction(self.trimAutoWhitespace_act)
        self.options_menu.addSeparator()
        self.options_menu.addAction(self.versionControl_act)
        self.options_menu.addSeparator()
        self.options_menu.addAction(self.wordWrap_act)
        self.options_menu.addAction(self.out_wordWrap_act)
        self.options_menu.addSeparator()
        self.options_menu.addAction(self.set_font_act)
        self.options_menu.addSeparator()
        self.options_menu.addAction(self.settingsFile_act)

        self.zoom_in_act = QAction(scriptEditor)
        self.zoom_in_act.setObjectName("zoom_in_act")
        self.zoom_out_act = QAction(scriptEditor)
        self.zoom_out_act.setObjectName("zoom_out_act")
        self.reset_zoom_act = QAction(scriptEditor)
        self.reset_zoom_act.setObjectName("reset_zoom_act")
        self.fold_all_act = QAction(scriptEditor)
        self.fold_all_act.setObjectName("fold_all_act")
        self.unfold_all_act = QAction(scriptEditor)
        self.unfold_all_act.setObjectName("unfold_all_act")
        self.fold_act = QAction(scriptEditor)
        self.fold_act.setObjectName("fold_act")
        self.unfold_act = QAction(scriptEditor)
        self.unfold_act.setObjectName("unfold_act")
        self.view_menu.addAction(self.always_ontop_act)
        self.view_menu.addSeparator()
        self.view_menu.addAction(self.showExplorer_act)
        self.view_menu.addAction(self.showOutline_act)
        self.view_menu.addSeparator()
        self.view_menu.addAction(self.showBreadcrumbs_act)
        self.view_menu.addAction(self.toggleMenus_act)
        self.view_menu.addAction(self.toggleEditorToolbar_act)
        self.view_menu.addSeparator()
        self.view_menu.addAction(self.showOutput_act)
        self.view_menu.addAction(self.outputBottom_act)
        self.view_menu.addSeparator()
        self.view_menu.addAction(self.fold_act)
        self.view_menu.addAction(self.unfold_act)
        self.view_menu.addAction(self.fold_all_act)
        self.view_menu.addAction(self.unfold_all_act)
        self.view_menu.addSeparator()
        self.view_menu.addAction(self.zoom_in_act)
        self.view_menu.addAction(self.zoom_out_act)
        self.view_menu.addAction(self.reset_zoom_act)

        self.run_menu.addSeparator()
        self.run_menu.addAction(self.clearHistory_act)
        self.run_menu.addAction(self.clear_exec_act)
        self.run_menu.addSeparator()
        self.run_menu.addAction(self.dir_act)
        self.run_menu.addAction(self.help_act)
        self.run_menu.addAction(self.print_act)
        self.run_menu.addAction(self.type_act)
        self.run_menu.addSeparator()
        self.run_menu.addAction(self.print_command_act)
        self.run_menu.addAction(self.execAll_act)
        self.run_menu.addAction(self.execLine_act)
        self.run_menu.addAction(self.execSel_act)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.tools_menu.menuAction())
        self.menubar.addAction(self.options_menu.menuAction())
        self.menubar.addAction(self.run_menu.menuAction())
        self.menubar.addAction(self.theme_menu.menuAction())
        self.menubar.addAction(self.view_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())
        self.toolBar.addAction(self.execAll_act)
        self.toolBar.addAction(self.execLine_act)
        self.toolBar.addAction(self.execSel_act)
        self.toolBar.addAction(self.clearHistory_act)

        self.retranslateUi(scriptEditor)
        QMetaObject.connectSlotsByName(scriptEditor)

    def retranslateUi(self, scriptEditor):
        scriptEditor.setWindowTitle(QApplication.translate("scriptEditor", "MainWindow", None))
        self.file_menu.setTitle(QApplication.translate("scriptEditor", "File", None))
        self.help_menu.setTitle(QApplication.translate("scriptEditor", "Help", None))
        self.tools_menu.setTitle(QApplication.translate("scriptEditor", "Edit", None))
        self.options_menu.setTitle(QApplication.translate("scriptEditor", "Options", None))
        self.theme_menu.setTitle(QApplication.translate("scriptEditor", "Theme", None))
        self.run_menu.setTitle(QApplication.translate("scriptEditor", "Run", None))
        self.view_menu.setTitle(QApplication.translate("scriptEditor", "View", None))
        self.toolBar.setWindowTitle(QApplication.translate("scriptEditor", "toolBar", None))
        self.clearHistory_act.setText(QApplication.translate("scriptEditor", "Clear output", None))
        self.clear_exec_act.setText(QApplication.translate("scriptEditor", "Clear output before execution", None))
        self.print_command_act.setText(QApplication.translate("scriptEditor", "Echo executed command", None))
        self.dir_act.setText(QApplication.translate("scriptEditor", "dir()", None))
        self.print_act.setText(QApplication.translate("scriptEditor", "print()", None))
        self.help_act.setText(QApplication.translate("scriptEditor", "help()", None))
        self.type_act.setText(QApplication.translate("scriptEditor", "type()", None))
        self.maya_cmds_act.setText(QApplication.translate("scriptEditor", "Maya commands", None))
        self.houdini_hou_act.setText(QApplication.translate("scriptEditor", "Houdini hou package", None))
        self.houdini_envs_act.setText(QApplication.translate("scriptEditor", "Houdini env variables", None))
        self.nuke_dev_guide_act.setText(QApplication.translate("scriptEditor", "Nuke dev guide", None))
        self.gaffer_docs_act.setText(QApplication.translate("scriptEditor", "Gaffer documentation", None))
        self.gaffer_node_reference_act.setText(QApplication.translate("scriptEditor", "Gaffer node / Python reference", None))
        self.quick_help_act.setText(QApplication.translate("scriptEditor", "Quick help", None))
        self.qt_docs_act.setText(QApplication.translate("scriptEditor", "Qt for Python", None))
        self.qt_modules_act.setText(QApplication.translate("scriptEditor", "Qt modules", None))
        self.save_act.setText(QApplication.translate("scriptEditor", "Save script", None))
        self.saveAs_act.setText(QApplication.translate("scriptEditor", "Save script as", None))
        self.load_act.setText(QApplication.translate("scriptEditor", "Open script", None))
        self.exit_act.setText(QApplication.translate("scriptEditor", "Exit", None))
        self.diffTool_act.setText(QApplication.translate("scriptEditor", "Compare with...", None))
        self.diffTool_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Shift+C", None))
        self.blenderManual_act.setText(QApplication.translate("scriptEditor", "Blender Python API", None))
        self.openManual_act.setText(QApplication.translate("scriptEditor", "GitHub", None))
        self.python_act.setText(QApplication.translate("scriptEditor", "Python documentation", None))
        self.quickHelp_act.setText(QApplication.translate("scriptEditor", "Quick help", None))
        self.saveSeccion_act.setText(QApplication.translate("scriptEditor", "Save session", None))
        self.closeAllTabs_act.setText(QApplication.translate("scriptEditor", "Close all tabs", None))
        self.tabToSpaces_act.setText(QApplication.translate("scriptEditor", "Tabs to spaces", None))
        self.spacesToTabs_act.setText(QApplication.translate("scriptEditor", "Spaces to tabs", None))
        self.showAutocomplete_act.setText(QApplication.translate("scriptEditor", "Show autocompletion", None))
        self.showAutocomplete_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Space", None))
        self.trimWhitespace_act.setText(QApplication.translate("scriptEditor", "Trim trailing whitespace", None))
        self.trimWhitespace_act.setShortcut(QApplication.translate("scriptEditor", "Alt+Shift+W", None))
        self.trimAutoWhitespace_act.setText(QApplication.translate("scriptEditor", "Trim auto whitespace", None))
        self.versionControl_act.setText(QApplication.translate("scriptEditor", "Version control (GIT)", None))
        self.versionControl_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Alt+G", None))
        self.toggleMenus_act.setText(QApplication.translate("scriptEditor", "Menus", None))
        self.toggleMenus_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Alt+M", None))
        self.toggleEditorToolbar_act.setText(QApplication.translate("scriptEditor", "Toolbar", None))
        self.always_ontop_act.setText(QApplication.translate("scriptEditor", "Always on top", None))
        self.settingsFile_act.setText(QApplication.translate("scriptEditor", "Open settings folder", None))
        self.editTheme_act.setText(QApplication.translate("scriptEditor", "Edit ...", None))
        self.shortcuts_act.setText(QApplication.translate("scriptEditor", "Shortcuts", None))
        self.donate_act.setText(QApplication.translate("scriptEditor", "Support", None))
        self.deleteLine_act.setText(QApplication.translate("scriptEditor", "Delete line(s)", None))
        self.duplicateLine_act.setText(QApplication.translate("scriptEditor", "Duplicate line(s)", None))
        self.about_act.setText(QApplication.translate("scriptEditor", "About", None))
        self.quit_act.setText(QApplication.translate("scriptEditor", "Quit", None))
        self.execAll_act.setText(QApplication.translate("scriptEditor", "Execute all", None))
        self.execLine_act.setText(QApplication.translate("scriptEditor", "Execute line", None))
        self.execSel_act.setText(QApplication.translate("scriptEditor", "Execute selected", None))
        self.wordWrap_act.setText(QApplication.translate("scriptEditor", "Word wrap", None))
        self.out_wordWrap_act.setText(QApplication.translate("scriptEditor", "Word wrap (output)", None))
        self.whitespace_act.setText(QApplication.translate("scriptEditor", "Render whitespace", None))
        self.themeFontOnTabs_act.setText(QApplication.translate("scriptEditor", "Use editor font on tabs", None))
        self.set_font_act.setText(QApplication.translate("scriptEditor", "Choose font...", None))
        self.clipboardManager_act.setText(QApplication.translate("scriptEditor", "Clipboard manager", None))
        self.clipboardManager_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Shift+V", None))
        self.copy_act.setText(QApplication.translate("scriptEditor", "Copy", None))
        self.cut_act.setText(QApplication.translate("scriptEditor", "Cut", None))
        self.paste_act.setText(QApplication.translate("scriptEditor", "Paste", None))
        self.addCursorsToLineEnds_act.setText(QApplication.translate("scriptEditor", "Add cursors to line ends", None))
        self.addCursorAbove_act.setText(QApplication.translate("scriptEditor", "Add cursor above", None))
        self.addCursorAbove_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Alt+Up", None))
        self.addCursorBelow_act.setText(QApplication.translate("scriptEditor", "Add cursor below", None))
        self.addCursorBelow_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Alt+Down", None))
        self.find_act.setText(QApplication.translate("scriptEditor", "Find", None))
        self.replace_act.setText(QApplication.translate("scriptEditor", "Replace", None))
        self.gitAction_act.setText(QApplication.translate("scriptEditor", "Git action", None))
        self.gitAction_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Shift+G", None))
        self.commandPalette_act.setText(QApplication.translate("scriptEditor", "Command palette...", None))
        self.commandPalette_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Shift+P", None))
        self.commandPalette_act.setStatusTip(QApplication.translate("scriptEditor", "Open command palette for quick searching (Ctrl+Shift+P)", None))
        self.gotoLine_act.setText(QApplication.translate("scriptEditor", "Go to line", None))
        self.goToSymbol_act.setText(QApplication.translate("scriptEditor", "Go to symbol", None))
        self.undo_act.setText(QApplication.translate("scriptEditor", "Undo", None))
        self.redo_act.setText(QApplication.translate("scriptEditor", "Redo", None))
        self.documentation_act.setText(QApplication.translate("scriptEditor", "Documentation", None))
        self.printHelp_act.setText(QApplication.translate("scriptEditor", "Help", None))
        self.moveLineUp_act.setText(QApplication.translate("scriptEditor", "Move line(s) up", None))
        self.moveLineDown_act.setText(QApplication.translate("scriptEditor", "Move line(s) down", None))
        self.selectLine_act.setText(QApplication.translate("scriptEditor", "Select line(s)", None))
        self.comment_cat.setText(QApplication.translate("scriptEditor", "Comment", None))
        self.add_quotes_act.setText(QApplication.translate("scriptEditor", "Add quotes", None))
        self.f_string_act.setText(QApplication.translate("scriptEditor", "f-string", None))
        self.showExplorer_act.setText(QApplication.translate("scriptEditor", "Explorer", None))
        self.showOutline_act.setText(QApplication.translate("scriptEditor", "Outline", None))
        self.showBreadcrumbs_act.setText(QApplication.translate("scriptEditor", "Breadcrumbs", None))
        self.showOutput_act.setText(QApplication.translate("scriptEditor", "Output", None))
        self.syntaxCheck_act.setText(QApplication.translate("scriptEditor", "Syntax check", None))
        self.outputBottom_act.setText(QApplication.translate("scriptEditor", "Output at the bottom", None))
        self.autoCloseDelimiters_act.setText(QApplication.translate("scriptEditor", "Auto close delimiters", None))
        self.quickTabSwitching_act.setText(QApplication.translate("scriptEditor", "Quick tab switching", None))
        self.showStatusTips_act.setText(QApplication.translate("scriptEditor", "Show status tips", None))
        self.autocomplete_act.setText(QApplication.translate("scriptEditor", "Autocomplete", None))
        self.fuzzy_autocomplete_act.setText(QApplication.translate("scriptEditor", "Fuzzy autocomplete", None))
        self.show_docstrings_act.setText(QApplication.translate("scriptEditor", "Show docstrings", None))
        self.highlightAllOccurrences_act.setText(QApplication.translate("scriptEditor", "Highlight all occurrences", None))
        self.occurrencesCaseSensitive_act.setText(QApplication.translate("scriptEditor", "Occurrences are case sensitive", None))
        self.preferSingleQuotes_act.setText(QApplication.translate("scriptEditor", "Prefer single quotes", None))
        self.selectNextOccurrence_act.setText(QApplication.translate("scriptEditor", "Select next occurrence", None))
        self.nextSelection_act.setText(QApplication.translate("scriptEditor", "Next highlight/selection", None))
        self.previousSelection_act.setText(
            QApplication.translate("scriptEditor", "Previous highlight/selection", None)
        )
        self.selectAllOccurrences_act.setText(QApplication.translate("scriptEditor", "Select all occurrences", None))
        self.zoom_in_act.setText(QApplication.translate("scriptEditor", "Zoom in", None))
        self.zoom_in_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl++", None))
        self.zoom_out_act.setText(QApplication.translate("scriptEditor", "Zoom out", None))
        self.zoom_out_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+-", None))
        self.reset_zoom_act.setText(QApplication.translate("scriptEditor", "Reset zoom", None))
        self.reset_zoom_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Alt+0", None))
        self.fold_all_act.setText(QApplication.translate("scriptEditor", "Fold all", None))
        self.fold_all_act.setShortcut(QApplication.translate("scriptEditor", "Alt+Shift+-", None))
        self.unfold_all_act.setText(QApplication.translate("scriptEditor", "Unfold all", None))
        self.unfold_all_act.setShortcut(QApplication.translate("scriptEditor", "Alt+Shift++", None))
        self.fold_act.setText(QApplication.translate("scriptEditor", "Fold", None))
        self.fold_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Alt+7", None))
        self.unfold_act.setText(QApplication.translate("scriptEditor", "Unfold", None))
        self.unfold_act.setShortcut(QApplication.translate("scriptEditor", "Ctrl+Alt+8", None))
